In [2]:
import pandas as pd

In [29]:
city_code = "/Users/shilpa/Desktop/Boringppl_project/WasteManagement/Data/city_level_codebook_0.csv"
city_code_df = pd.read_csv(city_code, encoding = 'utf-8')
city_code_df.head()

,regionID,iso3c,country_name,city_name,incomeID,measurement,units,year,source,comments
0,SAS,AFG,Afghanistan,Jalalabad,LIC,population_population_number_of_people,# of people,2015.0,"Islamic Republic of Afghanistan. 2015. ""State ...",NaN
1,SAS,IND,India,Vishakhapatnam,LMC,population_population_number_of_people,# of people,2011.0,"Census of India. 2014. ""Databook for PC 2011.""...",NaN
2,LCN,COL,Colombia,Cali,UMC,population_population_number_of_people,# of people,2005.0,CCAC (Climate and Clean Air Coalition). n.d.(d...,NaN
3,SAS,AFG,Afghanistan,Kabul,LIC,population_population_number_of_people,# of people,2016.0,"World Bank. 2016b. ""Islamic Republic of Afgha...",NaN
4,SAS,AFG,Afghanistan,Hirat,LIC,population_population_number_of_people,# of people,2015.0,"UN DESA (United Nations, Department of Economi...",NaN

In [31]:
city_data = "/Users/shilpa/Desktop/Boringppl_project/WasteManagement/Data/city_level_data_0_0.csv"
city_data_df = pd.read_csv(city_data, encoding = 'utf-8')
city_data_df.head()

,iso3c,region_id,country_name,income_id,city_name,additional_data_annual_budget_for_waste_management_year,additional_data_annual_solid_waste_budget_year,additional_data_annual_swm_budget_2017_year,additional_data_annual_swm_budget_year,additional_data_annual_waste_budget_year,...,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,waste_treatment_waterways_marine_percent
0,AFG,SAS,Afghanistan,LIC,Jalalabad,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
1,AFG,SAS,Afghanistan,LIC,Kandahar,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
2,AFG,SAS,Afghanistan,LIC,Mazar-E-Sharif,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
3,AFG,SAS,Afghanistan,LIC,Kabul,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,75.0,NaN,NaN,NaN,25.0,NaN
4,AFG,SAS,Afghanistan,LIC,HiratÂ,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN

In [49]:
city_data_df.columns

Index(['iso3c', 'region_id', 'country_name', 'income_id', 'city_name',
       'additional_data_annual_budget_for_waste_management_year',
       'additional_data_annual_solid_waste_budget_year',
       'additional_data_annual_swm_budget_2017_year',
       'additional_data_annual_swm_budget_year',
       'additional_data_annual_waste_budget_year',
       ...
       'waste_treatment_compost_percent',
       'waste_treatment_controlled_landfill_percent',
       'waste_treatment_incineration_percent',
       'waste_treatment_landfill_unspecified_percent',
       'waste_treatment_open_dump_percent', 'waste_treatment_other_percent',
       'waste_treatment_recycling_percent',
       'waste_treatment_sanitary_landfill_landfill_gas_system_percent',
       'waste_treatment_unaccounted_for_percent',
       'waste_treatment_waterways_marine_percent'],
      dtype='object', length=113)

In [6]:
csv_df_1.columns

Index(['regionID', 'iso3c', 'country_name', 'city_name', 'incomeID',
       'measurement', 'units', 'year', 'source', 'comments'],
      dtype='object')

In [37]:
result = pd.concat([city_code_df, city_data_df], axis=1, sort=False)
result.head(3)

,regionID,iso3c,country_name,city_name,incomeID,measurement,units,year,source,comments,...,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,waste_treatment_waterways_marine_percent
0,SAS,AFG,Afghanistan,Jalalabad,LIC,population_population_number_of_people,# of people,2015.0,"Islamic Republic of Afghanistan. 2015. ""State ...",NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
1,SAS,IND,India,Vishakhapatnam,LMC,population_population_number_of_people,# of people,2011.0,"Census of India. 2014. ""Databook for PC 2011.""...",NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
2,LCN,COL,Colombia,Cali,UMC,population_population_number_of_people,# of people,2005.0,CCAC (Climate and Clean Air Coalition). n.d.(d...,NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN

In [38]:
country_code = "/Users/shilpa/Desktop/Boringppl_project/WasteManagement/Data/country_level_codebook.csv"
country_code_df = pd.read_csv(country_code, encoding = 'utf-8')
country_code_df.head()

,regionID,iso3c,country_name,incomeID,measurement,units,year,source,comments
0,ECS,LUX,Luxembourg,HIC,special_waste_agricultural_waste_tons_year,tonnes/year,2014,"Eurostat. 2017a. ""Generation of waste by waste...",1; 2; 4
1,ECS,NOR,Norway,HIC,special_waste_agricultural_waste_tons_year,tonnes/year,2014,"Eurostat. 2017a. ""Generation of waste by waste...","1; HW includes waste containing oil, solvents,..."
2,MEA,MLT,Malta,HIC,special_waste_agricultural_waste_tons_year,tonnes/year,2014,"Eurostat. 2017a. ""Generation of waste by waste...",1; 2; 3; 4
3,EAS,NZL,New Zealand,HIC,special_waste_agricultural_waste_tons_year,tonnes/year,2014,"New Zealand, MFE (Ministry for the Environment...",CandD waste reported as over 3 million tonnes/...
4,EAS,JPN,Japan,HIC,special_waste_agricultural_waste_tons_year,tonnes/year,2010,"Modak, Prasad, Agamuthu Pariatamby, Jeffrey Se...",6 (excludes hazardous MSW); e-waste includes h...

In [39]:
country_data = "/Users/shilpa/Desktop/Boringppl_project/WasteManagement/Data/country_level_data_0.csv"
country_data_df = pd.read_csv(country_data, encoding = 'utf-8')
country_data_df.head()

,iso3c,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,...,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,waste_treatment_waterways_marine_percent,where_where_is_this_data_measured
0,ABW,LCN,Aruba,HIC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,89.0,NaN,NaN
1,AFG,SAS,Afghanistan,LIC,2.141361e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
2,AGO,SSF,Angola,LMC,1.030423e+11,51.8,6.7,4.4,11.50,11.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALB,ECS,Albania,UMC,1.347108e+10,51.4,4.5,4.8,15.21,9.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Some disposal sites
4,AND,ECS,Andorra,HIC,3.319880e+09,31.2,8.2,2.6,11.60,35.1,...,NaN,52.1,NaN,NaN,NaN,NaN,NaN,47.9,NaN,NaN

In [48]:
country_data_df.columns

Index(['iso3c', 'region_id', 'country_name', 'income_id', 'gdp',
       'composition_food_organic_waste_percent', 'composition_glass_percent',
       'composition_metal_percent', 'composition_other_percent',
       'composition_paper_cardboard_percent', 'composition_plastic_percent',
       'composition_rubber_leather_percent', 'composition_wood_percent',
       'composition_yard_garden_green_waste_percent',
       'other_information_information_system_for_solid_waste_management',
       'other_information_national_agency_to_enforce_solid_waste_laws_and_regulations',
       'other_information_national_law_governing_solid_waste_management_in_the_country',
       'other_information_ppp_rules_and_regulations',
       'other_information_summary_of_key_solid_waste_information_made_available_to_the_public',
       'population_population_number_of_people',
       'special_waste_agricultural_waste_tons_year',
       'special_waste_construction_and_demolition_waste_tons_year',
       'special_waste_e_waste_tons_year',
       'special_waste_hazardous_waste_tons_year',
       'special_waste_industrial_waste_tons_year',
       'special_waste_medical_waste_tons_year',
       'total_msw_total_msw_generated_tons_year',
       'waste_collection_coverage_rural_percent_of_geographic_area',
       'waste_collection_coverage_rural_percent_of_households',
       'waste_collection_coverage_rural_percent_of_population',
       'waste_collection_coverage_rural_percent_of_waste',
       'waste_collection_coverage_total_percent_of_geographic_area',
       'waste_collection_coverage_total_percent_of_households',
       'waste_collection_coverage_total_percent_of_population',
       'waste_collection_coverage_total_percent_of_waste',
       'waste_collection_coverage_urban_percent_of_geographic_area',
       'waste_collection_coverage_urban_percent_of_households',
       'waste_collection_coverage_urban_percent_of_population',
       'waste_collection_coverage_urban_percent_of_waste',
       'waste_treatment_anaerobic_digestion_percent',
       'waste_treatment_compost_percent',
       'waste_treatment_controlled_landfill_percent',
       'waste_treatment_incineration_percent',
       'waste_treatment_landfill_unspecified_percent',
       'waste_treatment_open_dump_percent', 'waste_treatment_other_percent',
       'waste_treatment_recycling_percent',
       'waste_treatment_sanitary_landfill_landfill_gas_system_percent',
       'waste_treatment_unaccounted_for_percent',
       'waste_treatment_waterways_marine_percent',
       'where_where_is_this_data_measured'],
      dtype='object')

In [46]:
world_merge = pd.merge(country_data_df, country_code_df, on='country_name')
world_merge.head(3)

,iso3c_x,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,...,waste_treatment_waterways_marine_percent,where_where_is_this_data_measured,regionID,iso3c_y,incomeID,measurement,units,year,source,comments
0,ABW,LCN,Aruba,HIC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LCN,ABW,HIC,waste_treatment_recycling_percent,tonnes/year,2013,"PricewaterhouseCoopers Aruba. 2014. ""Environme...",NaN
1,ABW,LCN,Aruba,HIC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LCN,ABW,HIC,total_msw_total_msw_generated_tons_year,tonnes/year,2013,"PricewaterhouseCoopers Aruba. 2014. ""Environme...",1 (2.34 kg/person/day)
2,ABW,LCN,Aruba,HIC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LCN,ABW,HIC,waste_treatment_unaccounted_for_percent,tonnes/year,NaN,NaN,NaN

In [50]:
world_merge.columns

Index(['iso3c_x', 'region_id', 'country_name', 'income_id', 'gdp',
       'composition_food_organic_waste_percent', 'composition_glass_percent',
       'composition_metal_percent', 'composition_other_percent',
       'composition_paper_cardboard_percent', 'composition_plastic_percent',
       'composition_rubber_leather_percent', 'composition_wood_percent',
       'composition_yard_garden_green_waste_percent',
       'other_information_information_system_for_solid_waste_management',
       'other_information_national_agency_to_enforce_solid_waste_laws_and_regulations',
       'other_information_national_law_governing_solid_waste_management_in_the_country',
       'other_information_ppp_rules_and_regulations',
       'other_information_summary_of_key_solid_waste_information_made_available_to_the_public',
       'population_population_number_of_people',
       'special_waste_agricultural_waste_tons_year',
       'special_waste_construction_and_demolition_waste_tons_year',
       'special_waste_e_waste_tons_year',
       'special_waste_hazardous_waste_tons_year',
       'special_waste_industrial_waste_tons_year',
       'special_waste_medical_waste_tons_year',
       'total_msw_total_msw_generated_tons_year',
       'waste_collection_coverage_rural_percent_of_geographic_area',
       'waste_collection_coverage_rural_percent_of_households',
       'waste_collection_coverage_rural_percent_of_population',
       'waste_collection_coverage_rural_percent_of_waste',
       'waste_collection_coverage_total_percent_of_geographic_area',
       'waste_collection_coverage_total_percent_of_households',
       'waste_collection_coverage_total_percent_of_population',
       'waste_collection_coverage_total_percent_of_waste',
       'waste_collection_coverage_urban_percent_of_geographic_area',
       'waste_collection_coverage_urban_percent_of_households',
       'waste_collection_coverage_urban_percent_of_population',
       'waste_collection_coverage_urban_percent_of_waste',
       'waste_treatment_anaerobic_digestion_percent',
       'waste_treatment_compost_percent',
       'waste_treatment_controlled_landfill_percent',
       'waste_treatment_incineration_percent',
       'waste_treatment_landfill_unspecified_percent',
       'waste_treatment_open_dump_percent', 'waste_treatment_other_percent',
       'waste_treatment_recycling_percent',
       'waste_treatment_sanitary_landfill_landfill_gas_system_percent',
       'waste_treatment_unaccounted_for_percent',
       'waste_treatment_waterways_marine_percent',
       'where_where_is_this_data_measured', 'regionID', 'iso3c_y', 'incomeID',
       'measurement', 'units', 'year', 'source', 'comments'],
      dtype='object')

In [54]:
world_city_merge = pd.merge(city_data_df, country_data_df,on='country_name')
world_city_merge.head()

,iso3c_x,region_id_x,country_name,income_id_x,city_name,additional_data_annual_budget_for_waste_management_year,additional_data_annual_solid_waste_budget_year,additional_data_annual_swm_budget_2017_year,additional_data_annual_swm_budget_year,additional_data_annual_waste_budget_year,...,waste_treatment_controlled_landfill_percent_y,waste_treatment_incineration_percent_y,waste_treatment_landfill_unspecified_percent_y,waste_treatment_open_dump_percent_y,waste_treatment_other_percent_y,waste_treatment_recycling_percent_y,waste_treatment_sanitary_landfill_landfill_gas_system_percent_y,waste_treatment_unaccounted_for_percent_y,waste_treatment_waterways_marine_percent_y,where_where_is_this_data_measured
0,AFG,SAS,Afghanistan,LIC,Jalalabad,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
1,AFG,SAS,Afghanistan,LIC,Kandahar,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
2,AFG,SAS,Afghanistan,LIC,Mazar-E-Sharif,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
3,AFG,SAS,Afghanistan,LIC,Kabul,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
4,AFG,SAS,Afghanistan,LIC,HiratÂ,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other

In [55]:
world_city_merge.columns

Index(['iso3c_x', 'region_id_x', 'country_name', 'income_id_x', 'city_name',
       'additional_data_annual_budget_for_waste_management_year',
       'additional_data_annual_solid_waste_budget_year',
       'additional_data_annual_swm_budget_2017_year',
       'additional_data_annual_swm_budget_year',
       'additional_data_annual_waste_budget_year',
       ...
       'waste_treatment_controlled_landfill_percent_y',
       'waste_treatment_incineration_percent_y',
       'waste_treatment_landfill_unspecified_percent_y',
       'waste_treatment_open_dump_percent_y',
       'waste_treatment_other_percent_y',
       'waste_treatment_recycling_percent_y',
       'waste_treatment_sanitary_landfill_landfill_gas_system_percent_y',
       'waste_treatment_unaccounted_for_percent_y',
       'waste_treatment_waterways_marine_percent_y',
       'where_where_is_this_data_measured'],
      dtype='object', length=163)