import pandas as pd

In [1]:
import pandas as pd
from IPython.display import display

In [2]:
city_code = "/Users/shilpa/Desktop/Boringppl_project/WasteManagement/Data/city_level_codebook_0.csv"
city_code_df = pd.read_csv(city_code, encoding = 'utf-8')
city_code_df.head()

,regionID,iso3c,country_name,city_name,incomeID,measurement,units,year,source,comments
0,SAS,AFG,Afghanistan,Jalalabad,LIC,population_population_number_of_people,# of people,2015.0,"Islamic Republic of Afghanistan. 2015. ""State ...",NaN
1,SAS,IND,India,Vishakhapatnam,LMC,population_population_number_of_people,# of people,2011.0,"Census of India. 2014. ""Databook for PC 2011.""...",NaN
2,LCN,COL,Colombia,Cali,UMC,population_population_number_of_people,# of people,2005.0,CCAC (Climate and Clean Air Coalition). n.d.(d...,NaN
3,SAS,AFG,Afghanistan,Kabul,LIC,population_population_number_of_people,# of people,2016.0,"World Bank. 2016b. ""Islamic Republic of Afgha...",NaN
4,SAS,AFG,Afghanistan,Hirat,LIC,population_population_number_of_people,# of people,2015.0,"UN DESA (United Nations, Department of Economi...",NaN

In [3]:
city_data = "/Users/shilpa/Desktop/Boringppl_project/WasteManagement/Data/city_level_data_0_0.csv"
city_data_df = pd.read_csv(city_data, encoding = 'utf-8')
city_data_df.head()

,iso3c,region_id,country_name,income_id,city_name,additional_data_annual_budget_for_waste_management_year,additional_data_annual_solid_waste_budget_year,additional_data_annual_swm_budget_2017_year,additional_data_annual_swm_budget_year,additional_data_annual_waste_budget_year,...,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,waste_treatment_waterways_marine_percent
0,AFG,SAS,Afghanistan,LIC,Jalalabad,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
1,AFG,SAS,Afghanistan,LIC,Kandahar,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
2,AFG,SAS,Afghanistan,LIC,Mazar-E-Sharif,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
3,AFG,SAS,Afghanistan,LIC,Kabul,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,75.0,NaN,NaN,NaN,25.0,NaN
4,AFG,SAS,Afghanistan,LIC,HiratÂ,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN

In [4]:
city_data_df.columns

Index(['iso3c', 'region_id', 'country_name', 'income_id', 'city_name',
       'additional_data_annual_budget_for_waste_management_year',
       'additional_data_annual_solid_waste_budget_year',
       'additional_data_annual_swm_budget_2017_year',
       'additional_data_annual_swm_budget_year',
       'additional_data_annual_waste_budget_year',
       ...
       'waste_treatment_compost_percent',
       'waste_treatment_controlled_landfill_percent',
       'waste_treatment_incineration_percent',
       'waste_treatment_landfill_unspecified_percent',
       'waste_treatment_open_dump_percent', 'waste_treatment_other_percent',
       'waste_treatment_recycling_percent',
       'waste_treatment_sanitary_landfill_landfill_gas_system_percent',
       'waste_treatment_unaccounted_for_percent',
       'waste_treatment_waterways_marine_percent'],
      dtype='object', length=113)

In [5]:
result = pd.concat([city_code_df, city_data_df], axis=1, sort=False)
result.head(3)

,regionID,iso3c,country_name,city_name,incomeID,measurement,units,year,source,comments,...,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,waste_treatment_waterways_marine_percent
0,SAS,AFG,Afghanistan,Jalalabad,LIC,population_population_number_of_people,# of people,2015.0,"Islamic Republic of Afghanistan. 2015. ""State ...",NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
1,SAS,IND,India,Vishakhapatnam,LMC,population_population_number_of_people,# of people,2011.0,"Census of India. 2014. ""Databook for PC 2011.""...",NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
2,LCN,COL,Colombia,Cali,UMC,population_population_number_of_people,# of people,2005.0,CCAC (Climate and Clean Air Coalition). n.d.(d...,NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN

In [6]:
country_code = "/Users/shilpa/Desktop/Boringppl_project/WasteManagement/Data/country_level_codebook.csv"
country_code_df = pd.read_csv(country_code, encoding = 'utf-8')
country_code_df.head()

,regionID,iso3c,country_name,incomeID,measurement,units,year,source,comments
0,ECS,LUX,Luxembourg,HIC,special_waste_agricultural_waste_tons_year,tonnes/year,2014,"Eurostat. 2017a. ""Generation of waste by waste...",1; 2; 4
1,ECS,NOR,Norway,HIC,special_waste_agricultural_waste_tons_year,tonnes/year,2014,"Eurostat. 2017a. ""Generation of waste by waste...","1; HW includes waste containing oil, solvents,..."
2,MEA,MLT,Malta,HIC,special_waste_agricultural_waste_tons_year,tonnes/year,2014,"Eurostat. 2017a. ""Generation of waste by waste...",1; 2; 3; 4
3,EAS,NZL,New Zealand,HIC,special_waste_agricultural_waste_tons_year,tonnes/year,2014,"New Zealand, MFE (Ministry for the Environment...",CandD waste reported as over 3 million tonnes/...
4,EAS,JPN,Japan,HIC,special_waste_agricultural_waste_tons_year,tonnes/year,2010,"Modak, Prasad, Agamuthu Pariatamby, Jeffrey Se...",6 (excludes hazardous MSW); e-waste includes h...

In [7]:
country_data = "/Users/shilpa/Desktop/Boringppl_project/WasteManagement/Data/country_level_data_0.csv"
country_data_df = pd.read_csv(country_data, encoding = 'utf-8')
country_data_df.head()

,iso3c,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,...,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,waste_treatment_waterways_marine_percent,where_where_is_this_data_measured
0,ABW,LCN,Aruba,HIC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11.0,NaN,89.0,NaN,NaN
1,AFG,SAS,Afghanistan,LIC,2.141361e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
2,AGO,SSF,Angola,LMC,1.030423e+11,51.8,6.7,4.4,11.50,11.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALB,ECS,Albania,UMC,1.347108e+10,51.4,4.5,4.8,15.21,9.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Some disposal sites
4,AND,ECS,Andorra,HIC,3.319880e+09,31.2,8.2,2.6,11.60,35.1,...,NaN,52.1,NaN,NaN,NaN,NaN,NaN,47.9,NaN,NaN

In [8]:
country_data_df.columns

Index(['iso3c', 'region_id', 'country_name', 'income_id', 'gdp',
       'composition_food_organic_waste_percent', 'composition_glass_percent',
       'composition_metal_percent', 'composition_other_percent',
       'composition_paper_cardboard_percent', 'composition_plastic_percent',
       'composition_rubber_leather_percent', 'composition_wood_percent',
       'composition_yard_garden_green_waste_percent',
       'other_information_information_system_for_solid_waste_management',
       'other_information_national_agency_to_enforce_solid_waste_laws_and_regulations',
       'other_information_national_law_governing_solid_waste_management_in_the_country',
       'other_information_ppp_rules_and_regulations',
       'other_information_summary_of_key_solid_waste_information_made_available_to_the_public',
       'population_population_number_of_people',
       'special_waste_agricultural_waste_tons_year',
       'special_waste_construction_and_demolition_waste_tons_year',
       'special_waste_e_waste_tons_year',
       'special_waste_hazardous_waste_tons_year',
       'special_waste_industrial_waste_tons_year',
       'special_waste_medical_waste_tons_year',
       'total_msw_total_msw_generated_tons_year',
       'waste_collection_coverage_rural_percent_of_geographic_area',
       'waste_collection_coverage_rural_percent_of_households',
       'waste_collection_coverage_rural_percent_of_population',
       'waste_collection_coverage_rural_percent_of_waste',
       'waste_collection_coverage_total_percent_of_geographic_area',
       'waste_collection_coverage_total_percent_of_households',
       'waste_collection_coverage_total_percent_of_population',
       'waste_collection_coverage_total_percent_of_waste',
       'waste_collection_coverage_urban_percent_of_geographic_area',
       'waste_collection_coverage_urban_percent_of_households',
       'waste_collection_coverage_urban_percent_of_population',
       'waste_collection_coverage_urban_percent_of_waste',
       'waste_treatment_anaerobic_digestion_percent',
       'waste_treatment_compost_percent',
       'waste_treatment_controlled_landfill_percent',
       'waste_treatment_incineration_percent',
       'waste_treatment_landfill_unspecified_percent',
       'waste_treatment_open_dump_percent', 'waste_treatment_other_percent',
       'waste_treatment_recycling_percent',
       'waste_treatment_sanitary_landfill_landfill_gas_system_percent',
       'waste_treatment_unaccounted_for_percent',
       'waste_treatment_waterways_marine_percent',
       'where_where_is_this_data_measured'],
      dtype='object')

In [9]:
world_merge = pd.merge(country_data_df, country_code_df, on='country_name')
world_merge.head(3)

,iso3c_x,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,...,waste_treatment_waterways_marine_percent,where_where_is_this_data_measured,regionID,iso3c_y,incomeID,measurement,units,year,source,comments
0,ABW,LCN,Aruba,HIC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LCN,ABW,HIC,waste_treatment_recycling_percent,tonnes/year,2013,"PricewaterhouseCoopers Aruba. 2014. ""Environme...",NaN
1,ABW,LCN,Aruba,HIC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LCN,ABW,HIC,total_msw_total_msw_generated_tons_year,tonnes/year,2013,"PricewaterhouseCoopers Aruba. 2014. ""Environme...",1 (2.34 kg/person/day)
2,ABW,LCN,Aruba,HIC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LCN,ABW,HIC,waste_treatment_unaccounted_for_percent,tonnes/year,NaN,NaN,NaN

In [10]:
world_merge.columns

Index(['iso3c_x', 'region_id', 'country_name', 'income_id', 'gdp',
       'composition_food_organic_waste_percent', 'composition_glass_percent',
       'composition_metal_percent', 'composition_other_percent',
       'composition_paper_cardboard_percent', 'composition_plastic_percent',
       'composition_rubber_leather_percent', 'composition_wood_percent',
       'composition_yard_garden_green_waste_percent',
       'other_information_information_system_for_solid_waste_management',
       'other_information_national_agency_to_enforce_solid_waste_laws_and_regulations',
       'other_information_national_law_governing_solid_waste_management_in_the_country',
       'other_information_ppp_rules_and_regulations',
       'other_information_summary_of_key_solid_waste_information_made_available_to_the_public',
       'population_population_number_of_people',
       'special_waste_agricultural_waste_tons_year',
       'special_waste_construction_and_demolition_waste_tons_year',
       'special_waste_e_waste_tons_year',
       'special_waste_hazardous_waste_tons_year',
       'special_waste_industrial_waste_tons_year',
       'special_waste_medical_waste_tons_year',
       'total_msw_total_msw_generated_tons_year',
       'waste_collection_coverage_rural_percent_of_geographic_area',
       'waste_collection_coverage_rural_percent_of_households',
       'waste_collection_coverage_rural_percent_of_population',
       'waste_collection_coverage_rural_percent_of_waste',
       'waste_collection_coverage_total_percent_of_geographic_area',
       'waste_collection_coverage_total_percent_of_households',
       'waste_collection_coverage_total_percent_of_population',
       'waste_collection_coverage_total_percent_of_waste',
       'waste_collection_coverage_urban_percent_of_geographic_area',
       'waste_collection_coverage_urban_percent_of_households',
       'waste_collection_coverage_urban_percent_of_population',
       'waste_collection_coverage_urban_percent_of_waste',
       'waste_treatment_anaerobic_digestion_percent',
       'waste_treatment_compost_percent',
       'waste_treatment_controlled_landfill_percent',
       'waste_treatment_incineration_percent',
       'waste_treatment_landfill_unspecified_percent',
       'waste_treatment_open_dump_percent', 'waste_treatment_other_percent',
       'waste_treatment_recycling_percent',
       'waste_treatment_sanitary_landfill_landfill_gas_system_percent',
       'waste_treatment_unaccounted_for_percent',
       'waste_treatment_waterways_marine_percent',
       'where_where_is_this_data_measured', 'regionID', 'iso3c_y', 'incomeID',
       'measurement', 'units', 'year', 'source', 'comments'],
      dtype='object')

In [11]:
world_city_merge = pd.merge(city_data_df, country_data_df,on='country_name')
world_city_merge.head()

,iso3c_x,region_id_x,country_name,income_id_x,city_name,additional_data_annual_budget_for_waste_management_year,additional_data_annual_solid_waste_budget_year,additional_data_annual_swm_budget_2017_year,additional_data_annual_swm_budget_year,additional_data_annual_waste_budget_year,...,waste_treatment_controlled_landfill_percent_y,waste_treatment_incineration_percent_y,waste_treatment_landfill_unspecified_percent_y,waste_treatment_open_dump_percent_y,waste_treatment_other_percent_y,waste_treatment_recycling_percent_y,waste_treatment_sanitary_landfill_landfill_gas_system_percent_y,waste_treatment_unaccounted_for_percent_y,waste_treatment_waterways_marine_percent_y,where_where_is_this_data_measured
0,AFG,SAS,Afghanistan,LIC,Jalalabad,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
1,AFG,SAS,Afghanistan,LIC,Kandahar,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
2,AFG,SAS,Afghanistan,LIC,Mazar-E-Sharif,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
3,AFG,SAS,Afghanistan,LIC,Kabul,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
4,AFG,SAS,Afghanistan,LIC,HiratÂ,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other

In [12]:
world_city_merge.columns

Index(['iso3c_x', 'region_id_x', 'country_name', 'income_id_x', 'city_name',
       'additional_data_annual_budget_for_waste_management_year',
       'additional_data_annual_solid_waste_budget_year',
       'additional_data_annual_swm_budget_2017_year',
       'additional_data_annual_swm_budget_year',
       'additional_data_annual_waste_budget_year',
       ...
       'waste_treatment_controlled_landfill_percent_y',
       'waste_treatment_incineration_percent_y',
       'waste_treatment_landfill_unspecified_percent_y',
       'waste_treatment_open_dump_percent_y',
       'waste_treatment_other_percent_y',
       'waste_treatment_recycling_percent_y',
       'waste_treatment_sanitary_landfill_landfill_gas_system_percent_y',
       'waste_treatment_unaccounted_for_percent_y',
       'waste_treatment_waterways_marine_percent_y',
       'where_where_is_this_data_measured'],
      dtype='object', length=163)

In [13]:
#grouped = world_merge.groupby('year')

#for name,group in grouped:
   #print(name)
   #print(group)

In [14]:
grouped = world_merge.groupby('year')
world_group_2017 = grouped.get_group('2017')
world_group_2017

#for name,group in grouped:
    #print(grouped.get_group('2017'))

,iso3c_x,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,...,waste_treatment_waterways_marine_percent,where_where_is_this_data_measured,regionID,iso3c_y,incomeID,measurement,units,year,source,comments
538,BTN,SAS,Bhutan,LMC,2.234759e+09,58.00,4.00,1.00,7.0,17.00,...,NaN,Source,SAS,BTN,LMC,special_waste_medical_waste_tons_year,tonnes/year,2017,"WHO (World Health Organization). 2017. ""Report...",NaN
905,DOM,LCN,Dominican Republic,UMC,7.366413e+10,51.00,6.00,3.00,10.0,16.00,...,NaN,Other,LCN,DOM,UMC,waste_treatment_open_dump_percent,tonnes/year,2017,"Dominican Republic, Ministry of Environment an...",NaN
911,DOM,LCN,Dominican Republic,UMC,7.366413e+10,51.00,6.00,3.00,10.0,16.00,...,NaN,Other,LCN,DOM,UMC,waste_treatment_sanitary_landfill_landfill_gas...,tonnes/year,2017,"Dominican Republic, Ministry of Environment an...",NaN
913,DOM,LCN,Dominican Republic,UMC,7.366413e+10,51.00,6.00,3.00,10.0,16.00,...,NaN,Other,LCN,DOM,UMC,waste_treatment_unaccounted_for_percent,tonnes/year,2017,NaN,OD: Calculated based on the sum of other treat...
918,DZA,MEA,Algeria,UMC,1.960348e+11,54.40,1.20,2.80,0.8,9.80,...,NaN,Disposal Site,MEA,DZA,UMC,waste_collection_coverage_rural_percent_of_hou...,Percent of population,2017,"Ouamane, Karim. 2017. General Director, Waste ...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3013,SGP,EAS,Singapore,HIC,2.991701e+11,10.51,0.93,19.12,32.3,14.86,...,NaN,NaN,EAS,SGP,HIC,composition_wood_percent,%,2017,"Singapore, NEA (National Environment Agency). ...",NaN
3014,SGP,EAS,Singapore,HIC,2.991701e+11,10.51,0.93,19.12,32.3,14.86,...,NaN,NaN,EAS,SGP,HIC,composition_yard_garden_green_waste_percent,%,2017,"Singapore, NEA (National Environment Agency). ...",NaN
3462,UGA,SSF,Uganda,LIC,2.748306e+10,74.50,0.80,0.60,10.6,6.00,...,NaN,NaN,SSF,UGA,LIC,waste_treatment_open_dump_percent,tonnes/year,2017,KCCA-IFC (Kampala Capital City Authority and I...,NaN
3467,UGA,SSF,Uganda,LIC,2.748306e+10,74.50,0.80,0.60,10.6,6.00,...,NaN,NaN,SSF,UGA,LIC,waste_treatment_recycling_percent,tonnes/year,2017,NaN,NaN
3468,UGA,SSF,Uganda,LIC,2.748306e+10,74.50,0.80,0.60,10.6,6.00,...,NaN,NaN,SSF,UGA,LIC,waste_treatment_sanitary_landfill_landfill_gas...,tonnes/year,2017,KCCA-IFC (Kampala Capital City Authority and I...,NaN

In [15]:
world_group_2017.columns

Index(['iso3c_x', 'region_id', 'country_name', 'income_id', 'gdp',
       'composition_food_organic_waste_percent', 'composition_glass_percent',
       'composition_metal_percent', 'composition_other_percent',
       'composition_paper_cardboard_percent', 'composition_plastic_percent',
       'composition_rubber_leather_percent', 'composition_wood_percent',
       'composition_yard_garden_green_waste_percent',
       'other_information_information_system_for_solid_waste_management',
       'other_information_national_agency_to_enforce_solid_waste_laws_and_regulations',
       'other_information_national_law_governing_solid_waste_management_in_the_country',
       'other_information_ppp_rules_and_regulations',
       'other_information_summary_of_key_solid_waste_information_made_available_to_the_public',
       'population_population_number_of_people',
       'special_waste_agricultural_waste_tons_year',
       'special_waste_construction_and_demolition_waste_tons_year',
       'special_waste_e_waste_tons_year',
       'special_waste_hazardous_waste_tons_year',
       'special_waste_industrial_waste_tons_year',
       'special_waste_medical_waste_tons_year',
       'total_msw_total_msw_generated_tons_year',
       'waste_collection_coverage_rural_percent_of_geographic_area',
       'waste_collection_coverage_rural_percent_of_households',
       'waste_collection_coverage_rural_percent_of_population',
       'waste_collection_coverage_rural_percent_of_waste',
       'waste_collection_coverage_total_percent_of_geographic_area',
       'waste_collection_coverage_total_percent_of_households',
       'waste_collection_coverage_total_percent_of_population',
       'waste_collection_coverage_total_percent_of_waste',
       'waste_collection_coverage_urban_percent_of_geographic_area',
       'waste_collection_coverage_urban_percent_of_households',
       'waste_collection_coverage_urban_percent_of_population',
       'waste_collection_coverage_urban_percent_of_waste',
       'waste_treatment_anaerobic_digestion_percent',
       'waste_treatment_compost_percent',
       'waste_treatment_controlled_landfill_percent',
       'waste_treatment_incineration_percent',
       'waste_treatment_landfill_unspecified_percent',
       'waste_treatment_open_dump_percent', 'waste_treatment_other_percent',
       'waste_treatment_recycling_percent',
       'waste_treatment_sanitary_landfill_landfill_gas_system_percent',
       'waste_treatment_unaccounted_for_percent',
       'waste_treatment_waterways_marine_percent',
       'where_where_is_this_data_measured', 'regionID', 'iso3c_y', 'incomeID',
       'measurement', 'units', 'year', 'source', 'comments'],
      dtype='object')

In [43]:
List_Of_Categories_In_Column = list(world_group_2017['income_id'].value_counts().index)

List_Of_Categories_In_Column

['UMC', 'HIC', 'LMC', 'LIC']

In [32]:
waste_generated = world_group_2017[['country_name', 
                                    'income_id', 
                                    'gdp', 
                                    'population_population_number_of_people',
                                    'composition_food_organic_waste_percent', 
                                    'composition_glass_percent',
                                    'composition_metal_percent', 
                                    'composition_other_percent',
                                    'composition_paper_cardboard_percent', 
                                    'composition_plastic_percent',
                                    'composition_rubber_leather_percent', 
                                    'composition_wood_percent',
                                    'composition_yard_garden_green_waste_percent']]
waste_generated.fillna(0).head(2)
#Nan values were converted too zeros because dtypes were float

,country_name,income_id,gdp,population_population_number_of_people,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,composition_rubber_leather_percent,composition_wood_percent,composition_yard_garden_green_waste_percent
538,Bhutan,LMC,2.234759e+09,686958.0,58.0,4.0,1.0,7.0,17.0,13.0,0.0,0.0,0.0
905,Dominican Republic,UMC,7.366413e+10,10528394.0,51.0,6.0,3.0,10.0,16.0,10.0,0.0,4.0,0.0

In [54]:
waste_generated_LIC = waste_generated.groupby('income_id').get_group('LIC').fillna(0)
waste_generated_LIC

,country_name,income_id,gdp,population_population_number_of_people,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,composition_rubber_leather_percent,composition_wood_percent,composition_yard_garden_green_waste_percent
1044,Ethiopia,LIC,5.234723e+10,99873033.0,87.60,0.80,1.2,4.40,3.80,2.30,0.0,0.0,0.0
1045,Ethiopia,LIC,5.234723e+10,99873033.0,87.60,0.80,1.2,4.40,3.80,2.30,0.0,0.0,0.0
1046,Ethiopia,LIC,5.234723e+10,99873033.0,87.60,0.80,1.2,4.40,3.80,2.30,0.0,0.0,0.0
1047,Ethiopia,LIC,5.234723e+10,99873033.0,87.60,0.80,1.2,4.40,3.80,2.30,0.0,0.0,0.0
2544,Nepal,LIC,1.985663e+10,28982771.0,52.39,4.36,1.9,7.12,18.21,15.14,0.9,0.0,0.0
2545,Nepal,LIC,1.985663e+10,28982771.0,52.39,4.36,1.9,7.12,18.21,15.14,0.9,0.0,0.0
2548,Nepal,LIC,1.985663e+10,28982771.0,52.39,4.36,1.9,7.12,18.21,15.14,0.9,0.0,0.0
2549,Nepal,LIC,1.985663e+10,28982771.0,52.39,4.36,1.9,7.12,18.21,15.14,0.9,0.0,0.0
2550,Nepal,LIC,1.985663e+10,28982771.0,52.39,4.36,1.9,7.12,18.21,15.14,0.9,0.0,0.0
2551,Nepal,LIC,1.985663e+10,28982771.0,52.39,4.36,1.9,7.12,18.21,15.14,0.9,0.0,0.0
2552,Nepal,LIC,1.985663e+10,28982771.0,52.39,4.36,1.9,7.12,18.21,15.14,0.9,0.0,0.0
2553,Nepal,LIC,1.985663e+10,28982771.0,52.39,4.36,1.9,7.12,18.21,15.14,0.9,0.0,0.0
2554,Nepal,LIC,1.985663e+10,28982771.0,52.39,4.36,1.9,7.12,18.21,15.14,0.9,0.0,0.0
3462,Uganda,LIC,2.748306e+10,35093648.0,74.50,0.80,0.6,10.60,6.00,7.60,0.0,0.0,0.0
3467,Uganda,LIC,2.748306e+10,35093648.0,74.50,0.80,0.6,10.60,6.00,7.60,0.0,0.0,0.0
3468,Uganda,LIC,2.748306e+10,35093648.0,74.50,0.80,0.6,10.60,6.00,7.60,0.0,0.0,0.0

In [53]:
waste_generated_LMC = waste_generated.groupby('income_id').get_group('LMC').fillna(0)
waste_generated_LMC.head(3)

,country_name,income_id,gdp,population_population_number_of_people,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,composition_rubber_leather_percent,composition_wood_percent,composition_yard_garden_green_waste_percent
538,Bhutan,LMC,2.234759e+09,6.869580e+05,58.0,4.0,1.0,7.0,17.0,13.0,0.0,0.0,0.0
1473,Indonesia,LMC,1.037864e+12,2.611155e+08,53.8,2.5,1.8,12.9,14.9,14.0,0.0,0.0,0.0
1495,India,LMC,2.466177e+12,1.071478e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
waste_generated_UMC = waste_generated.groupby('income_id').get_group('UMC').fillna(0)
waste_generated_UMC.head(3)
# Nan values converted to zeros

,country_name,income_id,gdp,population_population_number_of_people,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,composition_rubber_leather_percent,composition_wood_percent,composition_yard_garden_green_waste_percent
905,Dominican Republic,UMC,7.366413e+10,10528394.0,51.0,6.0,3.0,10.0,16.0,10.0,0.0,4.0,0.0
911,Dominican Republic,UMC,7.366413e+10,10528394.0,51.0,6.0,3.0,10.0,16.0,10.0,0.0,4.0,0.0
913,Dominican Republic,UMC,7.366413e+10,10528394.0,51.0,6.0,3.0,10.0,16.0,10.0,0.0,4.0,0.0

In [46]:
waste_generated_HIC = waste_generated.groupby('income_id').get_group('HIC').fillna(0)
waste_generated_HIC.head(3)
# Nan values converted to zeros

,country_name,income_id,gdp,population_population_number_of_people,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,composition_rubber_leather_percent,composition_wood_percent,composition_yard_garden_green_waste_percent
1362,"Hong Kong SAR, China",HIC,2.701054e+11,7305700.0,35.0,3.0,2.0,14.0,22.0,21.0,0.0,3.0,0.0
1611,Israel,HIC,2.878076e+11,8380100.0,34.0,3.0,3.0,16.0,24.0,18.0,0.0,0.0,2.0
1617,Israel,HIC,2.878076e+11,8380100.0,34.0,3.0,3.0,16.0,24.0,18.0,0.0,0.0,2.0

In [17]:
waste_information = world_group_2017[[
        'country_name', 
        'income_id', 'gdp', 
        'population_population_number_of_people',
        'other_information_information_system_for_solid_waste_management',
        'other_information_national_agency_to_enforce_solid_waste_laws_and_regulations',
        'other_information_national_law_governing_solid_waste_management_in_the_country',
        'other_information_ppp_rules_and_regulations',
        'other_information_summary_of_key_solid_waste_information_made_available_to_the_public']]
waste_information.fillna('No info')

# Converted Nan values to no info

,country_name,income_id,gdp,population_population_number_of_people,other_information_information_system_for_solid_waste_management,other_information_national_agency_to_enforce_solid_waste_laws_and_regulations,other_information_national_law_governing_solid_waste_management_in_the_country,other_information_ppp_rules_and_regulations,other_information_summary_of_key_solid_waste_information_made_available_to_the_public
538,Bhutan,LMC,2.234759e+09,686958.0,No,Yes,Yes,Yes,Yes
905,Dominican Republic,UMC,7.366413e+10,10528394.0,No,Yes,No,No,No info
911,Dominican Republic,UMC,7.366413e+10,10528394.0,No,Yes,No,No,No info
913,Dominican Republic,UMC,7.366413e+10,10528394.0,No,Yes,No,No,No info
918,Algeria,UMC,1.960348e+11,40606052.0,Yes,Yes,Yes,No info,Yes
...,...,...,...,...,...,...,...,...,...
3013,Singapore,HIC,2.991701e+11,5607283.0,Yes,Yes,Yes,Yes,Yes
3014,Singapore,HIC,2.991701e+11,5607283.0,Yes,Yes,Yes,Yes,Yes
3462,Uganda,LIC,2.748306e+10,35093648.0,No info,No info,No info,No info,No info
3467,Uganda,LIC,2.748306e+10,35093648.0,No info,No info,No info,No info,No info
3468,Uganda,LIC,2.748306e+10,35093648.0,No info,No info,No info,No info,No info

In [25]:
special_waste =  world_group_2017[[
        'country_name', 
        'income_id', 'gdp', 
        'population_population_number_of_people',
        'special_waste_agricultural_waste_tons_year',
        'special_waste_construction_and_demolition_waste_tons_year',
        'special_waste_e_waste_tons_year',
        'special_waste_hazardous_waste_tons_year',
        'special_waste_industrial_waste_tons_year',
        'special_waste_medical_waste_tons_year',
        'total_msw_total_msw_generated_tons_year', 
        'waste_collection_coverage_rural_percent_of_geographic_area']]
special_waste.fillna(0)

# Nan values converted to zeros

,country_name,income_id,gdp,population_population_number_of_people,special_waste_agricultural_waste_tons_year,special_waste_construction_and_demolition_waste_tons_year,special_waste_e_waste_tons_year,special_waste_hazardous_waste_tons_year,special_waste_industrial_waste_tons_year,special_waste_medical_waste_tons_year,total_msw_total_msw_generated_tons_year,waste_collection_coverage_rural_percent_of_geographic_area
538,Bhutan,LMC,2.234759e+09,686958.0,0.0,0.0,1457.5,0.0,1476.37,358.0,1.113141e+05,0.0
905,Dominican Republic,UMC,7.366413e+10,10528394.0,0.0,0.0,57000.0,0.0,0.00,0.0,4.063910e+06,0.0
911,Dominican Republic,UMC,7.366413e+10,10528394.0,0.0,0.0,57000.0,0.0,0.00,0.0,4.063910e+06,0.0
913,Dominican Republic,UMC,7.366413e+10,10528394.0,0.0,0.0,57000.0,0.0,0.00,0.0,4.063910e+06,0.0
918,Algeria,UMC,1.960348e+11,40606052.0,0.0,11000000.0,252000.0,330000.0,2547000.00,30000.0,1.237874e+07,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3013,Singapore,HIC,2.991701e+11,5607283.0,0.0,1609300.0,100000.0,446870.0,0.00,0.0,7.704300e+06,0.0
3014,Singapore,HIC,2.991701e+11,5607283.0,0.0,1609300.0,100000.0,446870.0,0.00,0.0,7.704300e+06,0.0
3462,Uganda,LIC,2.748306e+10,35093648.0,0.0,0.0,25000.0,0.0,0.00,0.0,7.045050e+06,0.0
3467,Uganda,LIC,2.748306e+10,35093648.0,0.0,0.0,25000.0,0.0,0.00,0.0,7.045050e+06,0.0
3468,Uganda,LIC,2.748306e+10,35093648.0,0.0,0.0,25000.0,0.0,0.00,0.0,7.045050e+06,0.0

In [28]:
waste_collection = world_group_2017[[
        'country_name', 
        'income_id', 'gdp', 
        'population_population_number_of_people',
        'waste_collection_coverage_rural_percent_of_households',
        'waste_collection_coverage_rural_percent_of_population',
        'waste_collection_coverage_rural_percent_of_waste',
        'waste_collection_coverage_total_percent_of_geographic_area',
        'waste_collection_coverage_total_percent_of_households',
        'waste_collection_coverage_total_percent_of_population',
        'waste_collection_coverage_total_percent_of_waste',
        'waste_collection_coverage_urban_percent_of_geographic_area',
        'waste_collection_coverage_urban_percent_of_households',
        'waste_collection_coverage_urban_percent_of_population',
        'waste_collection_coverage_urban_percent_of_waste'
]]
waste_collection.fillna(0)

# converted Nan values to zeros

,country_name,income_id,gdp,population_population_number_of_people,waste_collection_coverage_rural_percent_of_households,waste_collection_coverage_rural_percent_of_population,waste_collection_coverage_rural_percent_of_waste,waste_collection_coverage_total_percent_of_geographic_area,waste_collection_coverage_total_percent_of_households,waste_collection_coverage_total_percent_of_population,waste_collection_coverage_total_percent_of_waste,waste_collection_coverage_urban_percent_of_geographic_area,waste_collection_coverage_urban_percent_of_households,waste_collection_coverage_urban_percent_of_population,waste_collection_coverage_urban_percent_of_waste
538,Bhutan,LMC,2.234759e+09,686958.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,95.0
905,Dominican Republic,UMC,7.366413e+10,10528394.0,0.0,0.0,0.0,0.0,74.9,0.0,0.0,0.0,0.0,0.0,0.0
911,Dominican Republic,UMC,7.366413e+10,10528394.0,0.0,0.0,0.0,0.0,74.9,0.0,0.0,0.0,0.0,0.0,0.0
913,Dominican Republic,UMC,7.366413e+10,10528394.0,0.0,0.0,0.0,0.0,74.9,0.0,0.0,0.0,0.0,0.0,0.0
918,Algeria,UMC,1.960348e+11,40606052.0,0.0,87.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,87.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3013,Singapore,HIC,2.991701e+11,5607283.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0
3014,Singapore,HIC,2.991701e+11,5607283.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,0.0,0.0
3462,Uganda,LIC,2.748306e+10,35093648.0,0.0,0.0,0.0,0.0,0.0,0.0,37.5,0.0,0.0,0.0,0.0
3467,Uganda,LIC,2.748306e+10,35093648.0,0.0,0.0,0.0,0.0,0.0,0.0,37.5,0.0,0.0,0.0,0.0
3468,Uganda,LIC,2.748306e+10,35093648.0,0.0,0.0,0.0,0.0,0.0,0.0,37.5,0.0,0.0,0.0,0.0

In [31]:
waste_treatment = world_group_2017[[
        'country_name', 
        'income_id', 'gdp', 
        'population_population_number_of_people',
        'waste_treatment_anaerobic_digestion_percent',
        'waste_treatment_compost_percent',
        'waste_treatment_controlled_landfill_percent',
        'waste_treatment_incineration_percent',
        'waste_treatment_landfill_unspecified_percent',
        'waste_treatment_open_dump_percent', 'waste_treatment_other_percent',
        'waste_treatment_recycling_percent',
        'waste_treatment_sanitary_landfill_landfill_gas_system_percent',
        'waste_treatment_unaccounted_for_percent']]
waste_treatment.fillna(0)

# Nan values converted to zeros

,country_name,income_id,gdp,population_population_number_of_people,waste_treatment_anaerobic_digestion_percent,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent
538,Bhutan,LMC,2.234759e+09,686958.0,0.0,1.39,98.0,0.0,0.0,0.000000,0.0,0.86,0.0,0.000000
905,Dominican Republic,UMC,7.366413e+10,10528394.0,0.0,0.00,0.0,0.0,0.0,72.575831,0.0,8.20,0.1,19.124169
911,Dominican Republic,UMC,7.366413e+10,10528394.0,0.0,0.00,0.0,0.0,0.0,72.575831,0.0,8.20,0.1,19.124169
913,Dominican Republic,UMC,7.366413e+10,10528394.0,0.0,0.00,0.0,0.0,0.0,72.575831,0.0,8.20,0.1,19.124169
918,Algeria,UMC,1.960348e+11,40606052.0,0.0,1.00,2.0,0.0,0.0,0.000000,0.0,8.00,89.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3013,Singapore,HIC,2.991701e+11,5607283.0,0.0,0.00,0.0,37.0,2.0,0.000000,0.0,61.00,0.0,0.000000
3014,Singapore,HIC,2.991701e+11,5607283.0,0.0,0.00,0.0,37.0,2.0,0.000000,0.0,61.00,0.0,0.000000
3462,Uganda,LIC,2.748306e+10,35093648.0,0.0,0.00,0.0,0.0,0.0,87.000000,0.0,6.00,7.0,0.000000
3467,Uganda,LIC,2.748306e+10,35093648.0,0.0,0.00,0.0,0.0,0.0,87.000000,0.0,6.00,7.0,0.000000
3468,Uganda,LIC,2.748306e+10,35093648.0,0.0,0.00,0.0,0.0,0.0,87.000000,0.0,6.00,7.0,0.000000